// const BASEURL = "http://192.168.101.98:8080"; // 킨니
export const BASEURL = "http://localhost:8080"; // 집
export const getTask = BASEURL + "/user/1/list";
export const videoList = BASEURL + "/user/1/list";
export const videoInfo = BASEURL + "/video";
export const addKanban = BASEURL + "/list";
export const quizaccordion = BASEURL + "/video";
export const solvequiz = BASEURL + "/user/1/quiz";
// export const get = BASEURL + "example.com";
// export const get = BASEURL + "example.com";
// export const get = BASEURL + "example.com";
// export const get = BASEURL + "example.com";
// export const get = BASEURL + "example.com";
// export const get = BASEURL + "example.com";
